#!/bin/sh
set -e && export SHELLOPTS

( cd server
	cargo build \
		--release )

( cd client
	cargo install wasm-pack --root ../target
	../target/bin/wasm-pack build \
		-t web --no-pack --no-typescript \
		-d web/wasm )
