#!/bin/sh
cd() { command cd "$@" || exit; }

( cd server
	cargo build \
		--release )

( cd client
	wasm-pack build \
		-t web \
		-d web/wasm-pack \
		--no-pack --no-typescript
	rm web/wasm-pack/.gitignore )
